### ISSUE TITLE
I have host the challenge on online server with a given public IP how could i link it with my current subdomain 

### ISSUE THREAD

**Issue by ezracyber** [facebook/fbctf#171]
Like this https://challenge.rmit.me

**Comment by devkell** [comment]
Hi guys, i should appreciate the wonderful support from this repo,  i am too try to figure out on this issue. Currently i managed to host fbctf on VPS with a given Public ip adress. My question now is For now i hava already own my domain, so how cain i link my subdomain to my  VPS that hosts the challenge so that some one could go to my subdomain eg.   xxx.mydomain.com and access the challenge

**Comment by gsingh93** [comment]
You need to configure the DNS settings for your hosting provider/registrar. You need to create an A record that points your domain name to your server's public IP address. How you do this depends on which hosting provider you use.
