### ISSUE TITLE
Bulk adding to the DB

### ISSUE THREAD

**Issue by jeszicawii** [facebook/fbctf#188]
I've written a daemon that allows us to load 'modules' which are folders of 'levels' with each level being a json file.

The daemon uses an api I've got to add and remove from the database.
Sometimes the countries will turn red, sometimes they don't. I need to go into the admin panel, change a setting and they suddenly all appear.

This is also true with announcements. Any guidance on this?

**Comment by javuto** [comment]
Is this similar to the import/export capabilities? https://github.com/facebook/fbctf/pull/150

**Comment by jeszicawii** [comment]
Not quite, I have tried the import/export capabilities fork but it required a bit of changing to get working.
This is just a script that reads folders of json files and sticks them in the database,

**Comment by Ttech** [comment]
This sounds similar to my CTF question bundler script I have for FBCTF and CTFd, in the end dropping questions into the database preforms quite well and makes it a lot easier to deal.

**Comment by jeszicawii** [comment]
Interesting. @Ttech Are you using fbctf in production or development?

**Comment by jeszicawii** [comment]
So weird, just tried it a few times and it seems to be working. 
Do you have your bundler script up anywhere? Sounds cheeky but I'd love to have a peek!

**Comment by javuto** [comment]
I think the issue you are seeing is that you do add the data to the database but memcached is not updated so you need to run an action through the admin UI in order to have all in sync. It is not a problem with your browser, but with the data integrity.
My solution for this, would be to have a command line tool that does the inserting through the admin endpoint, instead of running direct SQL queries. For example, using python and requests or bash and curl.

**Comment by jeszicawii** [comment]
That's brilliant. Thank you.
This probably should have been the first thing I tried!
