### ISSUE TITLE
Docker image hanging

### ISSUE THREAD

**Issue by acjcool** [facebook/fbctf#215]
Hi,

I'm running Ubuntu 16.04.1 LTS and I'm trying to get the dev version running. There is no log files in /var/log/upstart/ or /var/log/docker/ so please let me know where I can find the error.log file or what else you need. I'm running docker version 1.12.1 build 23cf638

Steps:
I downloaded the zip file from GitHub and extracted it in my Home folder. I then ran the following commands (I'm not running sudo as I've added my user to the docker group):

Install command:
docker build --build-arg MODE=dev -t="fbctf_in_dev" .
Run command:
docker run -p 80:80 -p 443:443 -it fbctf_in_dev

Each time it gets stuck on 'Checking for tables which need an upgrade...'

I've attached what I could but open to add anything else but just let me know where to find it. I've previously run the docker image from qazbnm456/dockerized_fbctf successfully on this VM but things have changed now and docker fbctf version has been closed down. So, I have to work off this new one now

![bad gateway](https://cloud.githubusercontent.com/assets/3783663/18386756/3b9869d4-7699-11e6-9f01-1ee328b89d64.PNG)
[Install.txt](https://github.com/facebook/fbctf/files/463920/Install.txt)
[Run.txt](https://github.com/facebook/fbctf/files/463921/Run.txt)

**Comment by javuto** [comment]
We are investigating this issue, because it does affect not just the Docker image.

**Comment by matthewpurcell** [comment]
For the benefit of anyone else experiencing a 502 Bad Gateway error when deploying FBCTF, this appears to be due to a problem with the latest release of HHVM (3.15). I notice that @javuto has opened an issue ([#7333](https://github.com/facebook/hhvm/issues/7333)) on the [HHVM](https://github.com/facebook/hhvm) project.

I spent a day or so trying to figure out why FBCTF deployed fine earlier last week, but then had this problem from late last week. For the moment, the problem can be resolved by downgrading HHVM to 3.14.5 (the previous stable release, before 3.15).

For those not totally familiar with how to go about this process, this is what I did (which has worked).

Run these comments to remove HHVM, download the 3.14.5 (for Ubuntu 14.04), and then install the package:

```
cd ~ &&
apt-get autoremove hhvm &&
wget http://dl.hhvm.com/ubuntu/pool/main/h/hhvm/hhvm_3.14.5~trusty_amd64.deb &&
sudo dpkg -i hhvm_3.14.5~trusty_amd64.deb
```

(credit to [this comment](https://github.com/facebook/hhvm/issues/6385#issuecomment-148994502) which provided the basis for these commands)

You might get a warning about missing dependencies for HHVM. If that happens, they can be resolved by running:

`sudo apt-get -f install`

Once that completes, you should receive a message that HHVM has been installed.

Try visiting FBCTF, and hopefully it works (I didn't even have to restart nginx).

**Comment by javuto** [comment]
This should do it for now until the package is fixed: https://github.com/facebook/fbctf/pull/216
Thanks for looking into this and your insights @matthewpurcell

**Comment by javuto** [comment]
Given that this is mitigated for now (and awaiting a fix from HHVM and its latest package), we should be good to close.
