### ISSUE TITLE
Any code changes aren't reflecting

### ISSUE THREAD

**Issue by brandonbryan12** [facebook/fbctf#255]
I'm trying to make some contributions to the project, but none of the changes I'm making to the code seem to reflect when I reload.
I've tried vagrant reload and I've also tried clearing my browser cookies.

I have a second question, do you all use xDebug to debug? I'm trying to inspect a variable on the server-side, and xDebug doesn't seem to be working for me.

**Comment by gsingh93** [comment]
Are you editing the code on your local machine, or are you editing the code directly in /var/www/fbctf on the Vagrant VM? When you create the VM, the code is copied to /var/www/fbctf on the VM. Any code changes to your local repo won't take affect unless you use `unison` as described in the README. Also note that you need to run `grunt` if you're making JavaScript changes.

If you're wondering why we didn't just leave the repo where it is in `/vagrant` instead of moving it to `/var/www/fbctf`, it's because the `hh_client` (the program that type checks Hack code) doesn't work on NFS mounts, so we needed to move it.

**Comment by princemikee098** [comment]
Guys i have something to Ask Important? does anyone wants to Hel pme?
Thanks in Advance.

**Comment by brandonbryan12** [comment]
@gsingh93 I was editing /vagrant. Thanks for the help! It's working now. What debugging methods do you use?

@princemikee098 Go ahead and ask if it's related. If not, create a new issue

**Comment by javuto** [comment]
@brandonbryan12 glad that it works now!
@princemikee098 please create a new issue with your question. Thank you!
