### ISSUE TITLE
DigitalOcean Issue

### ISSUE THREAD

**Issue by mehranexpert** [facebook/fbctf#282]
i got some errors on DigitalOcean VPS ,  can i run it under it ?

**Comment by javuto** [comment]
What type of errors? Can you provide more details about the errors? Error output and logs would be great. There is nothing specific about the DigitalOcean VPS that may do the FBCTF platform to fail. Thanks.

**Comment by mehranexpert** [comment]
```
root@ctf:~/fbctf# vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
```

and keep on `==> default: Booting VM...`

**Comment by javuto** [comment]
Why are you using vagrant inside of a VPS?

**Comment by mehranexpert** [comment]
i just Read `Installation` and do it , what i must do on VPS ?

**Comment by javuto** [comment]
Vagrant is used to create a virtual environment to run the platform on. Any VPS, whether it is from DigitalOcean or any other provider, it is already an environment and instead of running ```vagrant up```, you need to run the provisioning command that vagrant uses. Whether you are setting up a production or development environment, that is entirely up to you. This is a really good guide that @mehnomy wrote: https://github.com/mehnomy/FBCTF-Ubuntu-Setup/wiki/Installing-FBCTF
