### ISSUE TITLE
[Question] Can I make it work with VMWare?

### ISSUE THREAD

**Issue by CodeMaxx** [facebook/fbctf#365]
Can I make some changes and get this to work with VMWare Fusion on a Mac?

**Comment by javuto** [comment]
Unfortunately we do not support this but it us possible to use VMware with vagrant. You need to enable the VMware Fusion support. Here are the steps to do it:

1. Buy a license to use vagrant with VMware Fusion in https://www.vagrantup.com/vmware/ 
2. Enable the Vagrant plugin for VMware Fusion with the command ```vagrant plugin install vagrant-vmware-fusion```
3. Install your license to be used with the plugin, for example with ```vagrant plugin license vagrant-vmware-fusion ~/license.lic``` if your license file is in ```~/license.lic```
4. Make some changes to the ```Vagrantfile``` such as adding:
```
config.vm.provider "vmware_fusion" do |v|
  v.vmx["memsize"] = "4096"
  v.vmx["numvcpus"] = "4"
end
```
That should be enough to make the platform work with VMware as provider for vagrant. You may need to make changes to the private IP address, otherwise you will run into conflicts for the subnet used by Virtualbox. Good luck!

**Comment by CodeMaxx** [comment]
Thanks! 

Saw the first step and installed VirtualBox 😝
