### ISSUE TITLE
Auto announcement when adding new challenge 

### ISSUE THREAD

**Issue by mabdi** [facebook/fbctf#443]
It's a good idea to make a announcement text in challenge add form. if it has set create a new announce and if not do nothing.

**Comment by javuto** [comment]
This is a good suggestion, but in my opinion will need a setting or option to enable/disable. There are scenarios when a level is created in the background and enabled later on. Maybe not an announcement, since those are supposed to be more important, but when a level is enabled, it can generate an entry in the Activity log. Thoughts @gsingh93?

**Comment by gsingh93** [comment]
Yea, this would be good to have. We can have an option to configure whether enabling a challenge would be an announcement, and otherwise we'll only show it in the activity log. I think these events should appear in the activity log unconditionally (without a config option).

**Comment by stevcoll** [comment]
@justinwray This is an interesting idea. Although we do have auto-announce now, I believe the idea here is you can set a custom announcement when creating the level, and it would be announced automatically when active? If this seems like a good idea it shouldn't be hard to implement with the new announcement code.

**Comment by justinwray** [comment]
Right -

So the basic functionality of auto announcing new levels etc. has been included in PR #513.  The idea of a customized message is compelling.  I will close this issue (as it was resolved) and open a new one specific to customized [automatic] announcements.
