### ISSUE TITLE
http instead of https

### ISSUE THREAD

**Issue by pinohans** [facebook/fbctf#480]
• commit 300091c
• Linux 16.04, work fine
• I want to use http instead of https. But when I log in it as admin, I cannot get /index.php?p=admin.

> Here is nginx config.

```
server_tokens off;

add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self'; frame-src 'self'; object-src 'none'";

server {
  listen 80;

  add_header X-Frame-Options DENY;
  add_header X-Content-Type-Options nosniff;
  add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";

  add_header Cache-Control "no-cache, no-store";
  add_header Pragma "no-cache";
  expires -1;

  root /var/www/fbctf/src;
  index index.php;
  location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass  unix:/var/run/hhvm/sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
  }
  error_page 400 401 402 403 404 500 /error.php;
  client_max_body_size 25M;
}
```

Thanks for help.

**Comment by contivero** [comment]
@pinohans Did you manage to do it? If so, how?
I tried changing the nginx config to use HTTP, but when I try to log in as admin, it just redirects me back to home.

Any help would be appreciated.

**Comment by stevcoll** [comment]
Of course it is highly recommended that you use HTTPS, as credentials and data can easily be intercepted over HTTP. However, as long as you understand that, you can make the following changes to use HTTP:

**/etc/nginx/sites-enabled/fbctf.conf**

- Comment out entire server block for port 80
- Replace port `443` in second server block with `80`
- Comment out `ssl on` line
- Restart nginx with `sudo service nginx restart`

**/var/www/fbctf/src/SessionUtils.php**

- Set `private static bool $s_secure` to `false`

If you are using Production mode, you'll need to rebuild the HHVM cache, as described [here](https://github.com/facebook/fbctf/wiki/FAQ#how-do-i-make-a-code-change-to-fbctf-in-production-mode). Otherwise, you should be good to go.

**Comment by contivero** [comment]
@stevcoll Thanks! that worked wonders.
I'm aware of the disadvantages, but it's just for a small, internal event, and we prefer the simplicity of HTTP for it. Anyway, thanks for the warning, and the help!
