### ISSUE TITLE
FBCTF Works in Bash on Windows (Beta)

### ISSUE THREAD

**Issue by callowaysutton** [facebook/fbctf#532]
On the current version (#503) and the Windows (Build 15063, Version 1703) with the Ubuntu Bash subsystem enabled I was able to set up FBCTF, does this mean that Ubuntu 14.04 isn't the only supported OS anymore?

**Comment by gsingh93** [comment]
We we say "supported OS", we mean operating systems we will provide support for, not operating systems that the platform will work on. There are lots of things that could break in various operating systems, and we do not have the time to debug each issue (although we will accept PRs to fix any issues as long as they don't break anything for supported operating systems).

We've chosen to only support Ubuntu 14.04 at this time because 1) It's a common distro that has long term support and 2) TravisCI supports it.

**Comment by crispy1996** [comment]
callowaysutton can you help me to setup fbctf in Ubuntu Bash subsystem maybe you can tell all the steps because i have encountered my warning and problem when trying to install it alone

**Comment by crispy1996** [comment]
callowaysutton can you help me to setup fbctf in Ubuntu Bash subsystem maybe you can tell all the steps because i have encountered many warnings and problems when trying to install it alone

**Comment by callowaysutton** [comment]
Sure, what is your problem?
