### ISSUE TITLE
Update to HHVM 3.21 and a more recent version of Ubuntu

### ISSUE THREAD

**Issue by fredemmott** [facebook/fbctf#544]
You're currently using 3.18 on Trusty; when 3.24 comes out towards the end of the year, 3.18 will be unsupported.

As [3.18 will be the last version to support Trusty](http://hhvm.com/blog/2017/02/15/hhvm-3-18.html), you're also going to need to stop using Trusty in your vagrant/docker images, so this upgrade will likely be more involved than most.

**Comment by fredemmott** [comment]
cc @gsingh93 , @justinwray

**Comment by justinwray** [comment]
Thank you for the heads up on HHVM/Ubuntu support.

We have done testing with the platform on Ubuntu 16.04 LTS and newer versions of HHVM.  Preliminary tests have been quite successful and many users have reported the same as well.

One of the biggest reasons we have not yet built the image against 16.04 or provided support for newer Ubuntu distribution is the lack of images for Travis-CI.

Travis-CI does not yet have any images newer than 14.04. However, the current image we are using is set to EOL in September of this year, so we will have to address Travis soon. We are exploring other options for Travis support as well, such as using docker containers instead of the base common-images.

Once Travis support is updated or the limitations are circumvented, we intend to explore upgrades of the project packages (HHVM included) and support of a newer version of Ubuntu.

**Comment by fredemmott** [comment]
We had a similar problem a few years back before Travis's last upgrade, and basically expect it to be recurring. Docker works fairly well for us, eg:

 - https://github.com/facebook/xhp-lib/blob/master/.travis.yml
 - https://github.com/facebook/xhp-lib/blob/master/.travis.sh

Something similar may work for you, and will avoid having the same problem again in a few years.

**Comment by gsingh93** [comment]
Docker is a good idea. I'm all for it.

**Comment by justinwray** [comment]
The platform has been updated to support Ubuntu 16.04 exclusively.  Along with the move to Ubuntu 16.04, the platform now uses the latest LTS of HHVM (3.21).

Please see #607 for more details.
