### ISSUE TITLE
Feature request: Admin cannot add team "members" names after registration period is over

### ISSUE THREAD

**Issue by Ysagi** [facebook/fbctf#583]
Hello.
First, I would like to thank you for an awesome CTF platform.

• Version of FBCTF installed: commit 1f236bba7e5e7a3e7169ff61037502a6928a94ba
• Linux system: Ubuntu 14.04 (x86_64)

The admin user can add teams after the registration period is over, by going to "Teams" and press "Add Team". The team is added, but the admin cannot add team "members" name to the team. It only says "No Team Names". This feature should be added. Under "Configuration "Players names" are "ON".

Best regards Matthew

**Comment by stevcoll** [comment]
@Ysagi From what I can tell this was by design. Admins do not have the ability to add team members, regardless of whether or not registration is turned on. That is only possible through the self-registration process.

As for whether or not admins should be able to add/remove/modify team members, that is an interesting feature request. Anybody else have feedback?
