### ISSUE TITLE
FACEBOOK BUG BOUNTY UNPAID FOR FOUR YEARS

### ISSUE THREAD

**Issue by donzaha** [facebook/fbctf#599]
I don't think I've made any mistake if I've said Facebook team is highly dishonest. If you've read about cases where the team had claimed to be unable to reproduce some reported bugs, you should question the team. I recently reported a high security bug and these guys immediately fixed the bug, telling me they could not reproduce the bug. I sent video proof of concept before the bug was reported and I even followed the fixing processes with video proof of fix sent to them. 

I have reported not one, not two, not three and not four bugs in the past and the last one I reported before the recent one was in December 2013; and in my Facebook whitehat dashboard, the progress column displays "Triaged" for one issue, "Mitigated" for another issue, "Fixed" for another one with the  status "Closed" with progress "Resolved" and "Description": "We have made a bounty decision about the triaged issue". However, these have been lying there for good four years without any bounty. I have sent messages but they've been ignoring my messages. 

You are not encouraging security researchers at all; it's just as if your bug bounty program is a hoax. A fellow security researcher once posted on Zuck's wall by virtue of this same denial. Why do you deny bugs? Why do you keep security researchers at work with the promise of bounty rewards? Why do you hold funds? Is it not a good decision to sue you?

**Comment by gsingh93** [comment]
Thanks for reaching out! Facebook's Whitehat Bug Bounty Program has paid out over $5 million dollars to hundreds of researchers since it started back in 2011. You can read more about the program and its history at https://www.facebook.com/notes/facebook-bug-bounty/facebook-bug-bounty-5-million-paid-in-5-years/1419385021409053/. Ultimately we rely entirely on researcher goodwill here. If people don't believe that we will triage their reports appropriately and fairly they won't submit issues to us. Given that it is never in our interest to mislead people about their reports. Doing so would inevitably prevent our program from being effective.

This repo is owned by Facebook but has no affiliation to the security team that runs the Whitehat program. Thus, if you have questions about reports you've previously submitted I would encourage you to reply to those reports directly. That is the best way to follow up with us, since we will have all the context about the details of your submissions.

**Comment by donzaha** [comment]
If you are looking for world liars, you will get all of them from
Facebook Security team. They are fucking liars. In fact, I have a
fresh proof that even if a 2-year old sees it, he will not think twice
before calling them liars. I will not grow weary until justice is done
to this issue.

**Comment by donzaha** [comment]
These guys have not treated my case. I will not rest until justice is
done to this case.
