### ISSUE TITLE
Change prod or dev install path away from 10.10.10.5?

### ISSUE THREAD

**Issue by david-rundle-bah** [facebook/fbctf#65]
How would I change the default IP address for either prod or dev instance to install in my lab's IP range?

**Comment by javuto** [comment]
If you install it in development mode, it will get installed in inside a virtual machine managed with vagrant. The configuration of that is in the Vagrantfile: https://github.com/facebook/fbctf/blob/master/Vagrantfile#L8
Also you can find more documentation about vagrant and networking here: https://github.com/facebook/fbctf/blob/master/Vagrantfile#L8

But if you install it in production mode, it will just use the configuration of the machine where it is being installed.

**Comment by dylanjacob** [comment]
To extend on what @javuto said, even though it says `https://10.10.10.5`, production mode will by default use your current ip address (assuming your interface is `eth0`, try running `ifconfig eth0` to get your current ip address)

**Comment by david-rundle-bah** [comment]
ok, I've created my self-signed certs, and the the prod provisioning script is running, but there's no SSL server running - SSH is the only connection according to netstat.  Hello, prod, are you here??

**Comment by gsingh93** [comment]
@david-rundle-bah Try starting nginx with `sudo service nginx start`, then check again with netstat.

**Comment by gsingh93** [comment]
Also, considering that it should have started automatically, were there any errors while provisioning it?

**Comment by david-rundle-bah** [comment]
I've tried this multiple times on different VM platforms, and still getting the same results.  I will capture the provisioning output on this go around.  Is there an option for verbose output?

**Comment by colbyjoe1919** [comment]
It's God.  No secrets no code.  God and that's just a taste.  You are out
of your league evil nerds no offense I hope.  I'm a nerd too I just like
star trek and quantum physics.  Torture induced suicide not my favorite
Saturday night but who am I to judge.

**Comment by colbyjoe1919** [comment]
No car
On May 17, 2016 8:47 AM, colbyjoe1919@gmail.com wrote:

It's God.  No secrets no code.  God and that's just a taste.  You are out
of your league evil nerds no offense I hope.  I'm a nerd too I just like
star trek and quantum physics.  Torture induced suicide not my favorite
Saturday night but who am I to judge.
On May 17, 2016 8:28 AM, "david-rundle-bah" <notifications@github.com>
wrote:

I've tried this multiple times on different VM platforms, and still getting
the same results. I will capture the provisioning output on this go around.
Is there an option for verbose output?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/facebook/fbctf/issues/65#issuecomment-219733570>

**Comment by colbyjoe1919** [comment]
For those that don't know when the big dog comes in and gets around a block
there will be more.  God is the ending and the beginning.  Your man got a
some demon info trust that.  You people have bodies you are already
superior you don't need to capitulate

**Comment by david-rundle-bah** [comment]
OK, found a workaround - installation script **requires** that the self-signed certs exist in the /fbctf file.  if you attempt to specify a path such as /home/catl/ssl/ssl.crt, the script attempts to load _homecatlsslssl.crt_ as the cert file.
