### ISSUE TITLE
How to remove it.

### ISSUE THREAD

**Issue by jhar8602** [facebook/fbctf#95]
How do i remove this piece of software? I ran the install, but i don't want to use it anymore.

**Comment by mehnomy** [comment]
Hello @jhar8602,

**If you installed this on a VM:**
-  you could simply just delete the VM and create a new Virtual Machine. 
**If its on a VPS:**
- you can reconfigure and reinstall Ubuntu 14.04 64x.

Kind Regards,
Byron Fisher

**Comment by jhar8602** [comment]
And if I installed it on a spare laptop I had laying around?
Is there any way to remove fbctf, or do I have to do a fresh reinstall of the os?

**Comment by no1rscyber** [comment]
Surely if its a spare laptop lying around then it would be just as easy to flatten the OS and reinstall a fresh OS?

**Comment by jhar8602** [comment]
Well, of course it would, but in that case I wouldn't learn anything new.

**Comment by mehnomy** [comment]
@jhar8602 

- `cd /etc/nginx/sites-enabled`
    - `rm fbctf.conf`
- `cd /var/www`
   - `rm fbctf`
- `sudo service nginx stop`
- `sudo apt-get remove nginx nginx-common`
   - `sudo apt-get purge nginx nginx-common`
   - `sudo apt-get auto remove`

or since the laptop you have installed it on has no value with nothing on it, then just reinstall the operating system.

Kind Regards,
Byron Fisher

**Comment by gsingh93** [comment]
@mehnomy's response covers some of it, other than that I'd look at the extra/provision.sh and extra/lib.sh scripts and remove any packages we've installed with `sudo apt-get remove <package name>`.
