### ISSUE TITLE
How to create competitions

### ISSUE THREAD

**Issue by Hacktast1c** [facebook/fbctf#99]
Platform built .... Interface is up ...... Now  how do I build competitions

Also, I have successfully created demo levels? What does it meat that I must deploy image to a different machine? ????

T.Y.I.A.

( ͡° ͜ʖ ͡°)

**Comment by mehnomy** [comment]
Hello @Hacktast1c,
What an interesting but complicated question you have asked, so let me try to explain.

Before even thinking of creating a competition the foundation first needs to be laid, within the Capture the Flag environment have you created the mini games, is the competition all based around the FBCTF?

**Mini games such as:**
 - Questions
 - Practical work (whiteboards are fun)
 - Creating other mini games using the language C.  

The demo mini games which you have used is so you get an understanding of how they're created, take a look at the code.
https://github.com/facebook/fbctf/tree/master/demo_levels/babys_first_bof

Its now time to create the competition, lets set the scene below:

**Setting the scene:**
**Event Type:** `Hackathon`
**Event Name:** `The Challenger`
**Target Audience:** `University and High School students`
**Event Location:** `RMIT University, Melbourne Australia`
**Sponsors:** `Facebook, Rackspace, Telstra, Coles, RMIT Uni`
**Prizes:** Explained below

**Explanation of the 6 key elements i have chosen above to set the scene:**
**Event Type / The Target Audience:** There are many types of competitions / events out there to create however since the target audience i have chosen are college/university students as well as high school students a `Hackathon` is a word every I.T student would know or has heard of.

**The Name** is always important as it needs to reflect what the competition is all about but also needs to be intriguing, so for instance i wouldn't choose a name like `Super Cool Hackathon` even though it relates to what the competition is about and i also wouldn't choose `RMIT Melbourne Australia Hackathon Competition` as its just too damn long. (me and my girlfriend sat for ages thinking of bad names and could only come up with good ones hehe)

**Event Location:** Needs to be a place where there is great public transport, and its not a needle in a hay stack (hard to find).

**Sponsors:** They are great for the marketing purpose as students are always looking to impress HeadHunters. Sponsors are also great to help fund the event for instance i have listed Coles who are one of the leading supermarkets in Australia. Please Note: This is not required to create a competition especially if we're talking small scale.

**Prizes:** Technology giveaways are always cool, or funds going towards something is always great remember that the prizes have to be well thought of as they're in groups so e.g a drone between 5 people doesn't really work. This is where your sponsors can help out, even thinking outside the box a technology company who are looking for Interns is a pretty cool prize for students who might be seeking for a Internship next year.

So we have now set the scene, and lets say 300 students have signed up and its now a few weeks from competition day but wait you haven't even thought about the environment which students could be held up in for up to 48hours, have you thought about the booze and the food?

So thinking back to our target audience we have a range ages with the students anyone from minimum 13 all the way to postgraduate students who might be in their 40s, anyone under the age of 18 can't be having alcohol so soft drinks, juices, slushies and water should be available either free or a gold coin donation at the most. For those who are like me and can't be coding with the lights on and without a beer in their hand well since we are set in Melbourne we will be using local brewed beer. (Locally as we can get great discounts if not free beer, and who doesn't love free beer)

Food well umm thats a hard one.. just kidding what type of coder doesn't binge out on pizza, and for those who don't well pre-packed sandwiches from Coles works a treat, otherwise they can always provide their own food.

`What does it mean that I must deploy image to a different machine?`
I don't quite understand, where are you seeing this?

**If you want to learn how to code there are some really cool free websites and resources out there:**

**Code Academy:**
Code Academy is a really fun and interactive learning environment which has on offer HTML, CSS, Python, Javascript, Jquery and Ruby, they even teach you how to use Popular APIs.
https://www.codecademy.com

**If you want to learn a language like C i would suggest reading a book like:**
The C Programming Language by Brian W. Kernighan, Dennis M. Ritchie
C Programming: A Modern Approach by K.N. King 

If there is anything else i can help you with please feel free on replying.

Kind Regards,
Byron Fisher

**Comment by Excis3** [comment]
Lol,
You have to deploy multiple vm's besides your CTF platform so not all challenges are held on the CTF server itself.
For example miss configured FTP challenges, weak Web Password challenges .....
The FB-CTF platform is just a point system to challenges you create. Where you can put in your solutions and get points for it.

This way you can create a competition.

**Comment by Hacktast1c** [comment]
Thanks you for your reply.  I figured the same. We maintain a Dashboard for internal training. 

So fbCTF will essentially allow me to create environments for each country !?

Ohh ... it's on !!!!!!!!!!

( ͡° ͜ʖ ͡°)

Thanks again ...... You guys rock.
